---
- hosts: all
  become: yes
  tasks:
    - name: Install pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python-pip
        - docker.io
    - name: Install docker package
      pip:
        name: docker

- hosts: build
  become: yes
  tasks:
    - git:
        repo: 'http://gitlab.6ax.su/6ax/docker-compose3.git'
        dest: /tmp/build_dir
        clone: yes
        update: yes
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: nexus.6ax.su
        username: "{{REPO_USER}}"
        password: "{{REPO_USER_PASSWD}}"
        reauthorize: yes
    - name: Build Docker image from Dockerfile and push to local registry
      docker_image:
        name: nexus.6ax.su/red5
        path: /tmp/build_dir/maven
        state: build
        push: yes

- hosts: prod
  become: yes
  tasks:
    - name: Create a RED5 container
      docker_container:
        name: RED5
        image: nexus.6ax.su/red5
        env:
            RED5_HOME: "/srv/red5-server"
        command: bash /srv/red5-server/red5.sh
        state: started
        ports:
            - "5080:5080"
            - "9999:9999"
            - "1935:1935"
        recreate: yes
